sonar.projectKey=jberbissbd_seguiment
sonar.organization=jberbissbd
sonar.projectName=Tutopy

sonar.sources=tutopy
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.10,3.11,3.12,3.13,3.14
sonar.python.coverage.reportPaths=coverage.xml
