from pathlib import Path

try:
    import tomllib
except ImportError:  # Python 3.10
    import tomli as tomllib

from scripts.check_release_version import main as check_release_version
from scripts.project_version import read_project_version


ROOT = Path(__file__).parents[1]


def test_release_tag_ha_de_coincidir_amb_pyproject(capsys):
    assert check_release_version(f"v{read_project_version()}") == 0
    assert check_release_version("v9.9.9") == 1
    assert "no coincideix" in capsys.readouterr().err


def test_versio_del_projecte_es_llegida_des_del_pyproject():
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    assert read_project_version() == project["project"]["version"]


def test_release_workflow_construeix_els_tres_sistemes():
    workflow = (ROOT / ".github/workflows/release.yml").read_text(encoding="utf-8")
    assert "windows-latest" in workflow
    assert "ubuntu-22.04" in workflow
    assert "macos-15-intel" in workflow
    assert "pyinstaller --clean --noconfirm tutopy.spec" in workflow
    assert 'tags:\n      - "v*"' in workflow


def test_accions_del_release_utilitzen_node_24():
    workflow = (ROOT / ".github/workflows/release.yml").read_text(encoding="utf-8")
    assert "actions/checkout@v5" in workflow
    assert "actions/setup-python@v6" in workflow
    assert "actions/upload-artifact@v6" in workflow
    assert "actions/download-artifact@v7" in workflow


def test_spec_es_onefile_i_no_inclou_base_de_dades():
    spec = (ROOT / "tutopy.spec").read_text(encoding="utf-8")
    assert "COLLECT(" not in spec
    assert 'name="Tutopy"' in spec
    assert "seguiment.db" not in spec
    assert "console=False" in spec


def test_spec_inclou_icona_i_recursos_visuals():
    spec = (ROOT / "tutopy.spec").read_text(encoding="utf-8")
    assert '("tutopy/ui/assets", "tutopy/ui/assets")' in spec
    assert '"tutopy/ui/assets/tutopy.ico"' in spec
    assert '"tutopy/ui/assets/tutopy.png"' in spec
    assert "icon=icon_path" in spec


def test_icones_d_empaquetatge_existeixen():
    assert (ROOT / "tutopy/ui/assets/tutopy.ico").is_file()
    assert (ROOT / "tutopy/ui/assets/tutopy.png").is_file()


def test_versio_de_pyinstaller_esta_fixada():
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    dependencies = project["project"]["optional-dependencies"]["build"]
    assert "pyinstaller==6.21.0" in dependencies


def test_dependencies_de_build_especifiques_de_cada_sistema_estan_fixades():
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    dependencies = project["project"]["optional-dependencies"]["build"]
    assert "macholib==1.16.4; sys_platform == 'darwin'" in dependencies
    assert "pefile==2024.8.26; sys_platform == 'win32'" in dependencies
    assert "pywin32-ctypes==0.2.3; sys_platform == 'win32'" in dependencies

    lock = (ROOT / "requirements-build.lock").read_text(encoding="utf-8")
    assert "macholib==1.16.4" in lock
    assert "pefile==2024.8.26" in lock
    assert "pywin32-ctypes==0.2.3" in lock


def test_exportacio_docx_forma_part_de_les_dependencies_i_del_build():
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    assert "python-docx==1.2.0" in project["project"]["dependencies"]
    assert "python-docx==1.2.0" in (
        ROOT / "requirements-build.lock"
    ).read_text(encoding="utf-8")


def test_workflows_i_lock_utilitzen_python_312():
    for workflow_name in ("ci.yml", "release.yml"):
        workflow = (ROOT / ".github/workflows" / workflow_name).read_text(
            encoding="utf-8"
        )
        assert 'python-version: "3.12"' in workflow
        assert 'python-version: "3.10"' not in workflow
    lock = (ROOT / "requirements-dev.lock").read_text(encoding="utf-8")
    assert "generated by pip-compile with Python 3.12" in lock


def test_ci_genera_cobertura_i_executa_sonarcloud():
    workflow = (ROOT / ".github/workflows/ci.yml").read_text(encoding="utf-8")
    assert "fetch-depth: 0" in workflow
    assert "--cov-report=xml:coverage.xml" in workflow
    assert "SonarSource/sonarqube-scan-action@v7" in workflow
    assert "-Dsonar.projectVersion=${{ steps.project.outputs.version }}" in workflow


def test_configuracio_sonar_separa_fonts_tests_i_importa_cobertura():
    configuration = (ROOT / "sonar-project.properties").read_text(encoding="utf-8")
    assert "sonar.sources=tutopy" in configuration
    assert "sonar.tests=tests" in configuration
    assert "sonar.python.coverage.reportPaths=coverage.xml" in configuration
    assert "sonar.python.version=3.10,3.11,3.12,3.13,3.14" in configuration
