name: Build

on:
  release:
    branches: ["master"]

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller --onefile src/build.spec
            OUT_FILE_NAME: tutopy_windows
            ASSET_MIME: application/vnd.microsoft.portable-executable


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pyinstaller
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.OUT_FILE_NAME}}
        path: dist


